#!/bin/sh

set -e

# Add diversions for manpages-*
case "$1" in
  install|upgrade)
    for l10n in de es fi fr hu id pl
    do
	for manpage in init.8 halt.8 poweroff.8 reboot.8 runlevel.8 shutdown.8 telinit.8
	do
	    mandir=/usr/share/man/${l10n}/man${manpage##*.}
	    dpkg-divert --package sysvinit-init-diversity --add --rename \
			--divert ${mandir}/${manpage}.dist ${mandir}/${manpage}.gz
	done
    done
    ;;
    *) ;;

esac

#DEBHELPER#

exit 0
